name: AzanApp
options:
  bundleIdPrefix: com.imti
targets:
  AzanApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imti.AzanApp
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        NSLocationWhenInUseUsageDescription: "We need your location to accurately calculate Azan times and find the Qibla."
        NSLocationAlwaysAndWhenInUseUsageDescription: "We need your location to accurately calculate Azan times and find the Qibla."
    dependencies:
      - target: AzanWidgetExtension

  AzanWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Widget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imti.AzanApp.widget
    info:
      path: Widget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: "com.apple.widgetkit-extension"
